version: '3'

services:
  testapp:
   image: trbr1800/node-backend
   ports:
     - 5000:5000
   environment:
     - SERVICE_PORTS=5000
   deploy:
     replicas: 15
     update_config:
       parallelism: 3
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
   networks:
     - balance

  balancer:
    image: trbr1800/haproxy-server
    depends_on:
      - testapp
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - balance
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  balance:
    driver: overlay