version: '3'

services:
  testapp:
   image: trbr1800/nginx-server
   ports:
     - 5000:5000
   deploy:
     replicas: 15
     restart_policy:
       max_attempts: 3
       condition: on-failure       
     update_config:
       parallelism: 3
       delay: 10s
   networks: 
    - balance 
  
  balancer:
    image: trbr1800/nginx-server
    ports:
      - 80:80
    depends_on:
      - testapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay